  
version: '3'
services:
    job-finder:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            - "9229:9229"
        restart: always
        volumes:
            - ./src:/usr/app/src
    job-finder-api:
        build:
            context: ../job-finder-api
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        volumes:
            - ../job-finder-api/src:/usr/src