  
version: '3'
volumes:
    cloud_database_data:
      driver: local
services:
    job-finder:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            - "9229:9229"
        restart: always
        volumes:
            - ./src:/usr/app/src
    job-finder-api:
        build:
            context: ../job-finder-api
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        volumes:
            - ../job-finder-api/src:/usr/src
    db:    
        image: postgres
        volumes:
            - cloud_database_data:/var/lib/postgresql/data
            - ../job-finder-api/database/init_scripts:/docker-entrypoint-initdb.d/
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=job_finder
        ports:
            - "5432:5432"